[package]
name = "pdf_core"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.9"
lopdf = "0.33"
thiserror = "1.0"
docx-rs = "0.4"
pdfium-render = "0.8.37"

[dev-dependencies]
anyhow = "1.0"
